### ISSUE TITLE
Support references between Terraform modules

### ISSUE THREAD

**Issue by VladRassokhin** [VladRassokhin/intellij-hcl#25]
- [x] `module` block
  - [x] Relative path
  - [x] Remote (using get command ?)
- [ ] `terraform_remote_state` resource
  - [ ] artifactory
  - [ ] atlas
  - [ ] consul
  - [ ] etcd
  - [ ] http
  - [ ] s3
  - [ ] swift

Related documentation:
`module` block - [`get` command](https://www.terraform.io/docs/commands/get.html)

**Comment by mkuzmin** [comment]
I don't think the plugin should download modules automatically.
But after `terraform get` is launched externally, it would be cool to read them from `.terraform/modules/`

**Comment by mkuzmin** [comment]
How does remote state relate to this feature?

**Comment by scream314** [comment]
Hi!
The remote modules are detected correctly, as long as they are in the git repo's root.
In case they are in a subdir (like in https://github.com/opencredo/letsencrypt-terraform), it fails to detect them.
I think the plugin should try to look for `//`s in the module `source` (like in `source = "github.com/opencredo/letsencrypt-terraform//modules/acme-cert-request"`) and if there is a `//`, look for the module in the path after `//`.

**Comment by VladRassokhin** [comment]
@scream314 From next plugin release subdirectories would be also successfully detected

**Comment by Kurry** [comment]
@VladRassokhin Thanks for the update on this!

**Comment by darrenhaken** [comment]
Hey all is this the same as using remote state?

```
data "terraform_remote_state" "global" {
  backend = "s3"
  config {
    bucket = "state-bucket"
    key = "key.tfstate"
    region = "region"
  }
}
```

I'm unable to get autocomplete/validation when using any state from another state file like this.

**Comment by iTsFILIPOficial** [comment]
@VladRassokhin Is the fix for completion of remote modules been merged? I don't seem to be able to auto-complete any variables or outputs from remote directories by using local ones works.

**Comment by VladRassokhin** [comment]
@iTsFILIPOficial for remote modules it's supported for several months already, if you have some problems please create a new issue. Also ensure to run `terraform get`

**Comment by nicolas-rey** [comment]
Actualy, after a `terraform get` the auto-completion not work

> WARN - .terraform.config.model.Module - Terraform Module 'remote-module' with source 'git::ssh://git@git.local/test/module-terraform.git' directory not found locally under 'PsiDirectory:/opt/poc/terraform', use `terraform get` to fetch modules.

The function _computeModuleStorageName_ get the md5 hash by: `"root.$path-$source"`
But `terraform get` set the hash by : `"1.$path;$source"`

**Comment by VladRassokhin** [comment]
@nicolas-rey Thanks for sharing. Probably there was some change in Terraform code, I'll take a look.

**Comment by VladRassokhin** [comment]
Fixed modules referencing, would be available in upcoming release.

**Comment by alxgrk** [comment]
Hi there, 

with the fix introduced in 0.6.12 the referencing of local modules seems to got broken.
The following example:

**_structure:_**
- root
  - terraform.tfvars
  - module_a
    - output.tf
  - module_b
    - .terraform
      - modules
        - modules.json
        - {{my-hashed-module}}
          - output.tf
    - main.tf
    - terraform.tfvars
  - ...

**_--- module_a/output.tf ---_**
```yaml
output "foo" {
  value = "bar"
}
```
**_--- module_b/main.tf ---_**
```yaml
module "module_a" {
  source = "../module_a"
}

resource "some_resource" "my-resource" {
  foo = "${module.module_a.foo}"
}
```

As you might have already seen, I'm using terragrunt in my project, to be able to plan etc. module_b on it's own (executing terragrunt in the module's directory) or all modules together (executing terragrunt in the root directory).
Since the reference from module_b to module_a is a local file reference ("../module_a"), I would have expected auto-completion and referencing to consider the actual file in module_a.

However, with the update to 0.6.12 the plugin began to only consider files in _".terraform/modules/{{my-hashed-module}}"_. This becomes problematic, when I want to edit the original file in module_a by "ctrl + left-click" jumping to it - which brings me to the generated file in _".terraform/modules/{{my-hashed-module}}"_. 
It is also a problem, because Intellij will mark the module as non-existent as long as I didn't run any terraform command to generate the ".terraform" directory contents.

I currently reverted back to 0.6.10, which did support the wanted behaviour.

Is there any chance, that you can try out yourself and fix the issue?

Thanks in advance.
Regards, 
Alex

**Comment by VladRassokhin** [comment]
@alxgrk AFAIR since 0.6.14 (or even 0.6.13) relative module paths fixed and plugin would navigate to plugin source, not `.terraform/modules/HASH/`.

**Comment by VladRassokhin** [comment]
I'm closing issue since 'module' blocks are supported and there's no visible API in Terraform to fetch remote states.
