### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by kir4h** [VladRassokhin/intellij-hcl#273]
Sorry for not respecting the template, but since it's rather a question it doesn't make much sense.

Which is the status of this project? I'm a newcomer and noticed that at some point commits stopped but releases are still coming out. Was development moved to some `JetBrains` private repository and this repository is open for filing issues? `README.md` doesn't reflect this, so just wondering.

Thanks!

**Comment by G-Rath** [comment]
@kir4h From what I've picked up, I believe the plugin has been internalised by JetBrains, and that @VladRassokhin is contract-bound to not discuss, which is why issues & comments asking about the state of the repo are being ignored.

As Vlad works for JetBrains as one of their senior devs, my guess is that this plugin started as a side project to explore HCL support in IntelliJ, and that JetBrains decided to pull into their internal wing when it was clear how promising a plugin it was.

Hopefully what's happening now is that things are being ironed out before an official posting & rebranding occurs by JetBrains, at which point we'll see the plugin get some form of update (i.e the README being updated to point to YouTrack if JetBrains decides to track issues for it there).

It could also be that they're looking to integrate this into Space, but 🤷‍♂ 

Personally, I think the state this plugin currently is in is a little sad, as if the source code remained up to date, people like me would be happily contributing towards it - but it's a tough one for JetBrains: some people would be understandably angry if they were allowed to work on an open source project only to have it (and their contributed code) suddenly turn private due to contracts signed 6 months beforehand (if JetBrains didn't say that was going to happen), or otherwise people might not want to contribute to a project they've been told will turn private some day in the future (if JetBrains did tell).

Regardless, this is the state we're in: the plugin is on JetBrains rader and getting some love, but this repository is only good as an issue tracker for bugs right now.

**Comment by kir4h** [comment]
Thanks @G-Rath. That's the impression I got, that at some point development was moved out from here for some reason. But I couldn't find any statement so I was curious if the reason was clear.

No matter the reason, I think either @VladRassokhin or Jetbrains should update the `README` on this project to reflect current status so that any developer landing here is pretty clear about it. (if PR or new issues are welcome or this repository is totally deprecated).

**Comment by VladRassokhin** [comment]
Hi, thanks for reminding about that.
Hopefully recent commit https://github.com/VladRassokhin/intellij-hcl/commit/0bd7ddd6153e62f7f7c92beb7c6b8de7880a6586 answers some questions.


>is contract-bound to not discuss

Nope, I just had no time to publish update (it was prepared two months ago)

>as if the source code remained up to date, people like me would be happily contributing towards it 

Unfortunately, I've seen almost zero contributions over all four years of plugin, so closing sources is fine for me.

>some people would be understandably angry if they were allowed to work on an open source project only to have it (and their contributed code) suddenly turn private due to contracts signed 6 months beforehand

Don't get it. I've asked all contributors about that and asked to sign CLA somewhere around February. Nothing is 'suddenly' turns private. I've just not had time to communicate that publically.


>this repository is only good as an issue tracker for bugs right now.

Exactly.

**Comment by kir4h** [comment]
Thanks for the clarifications @VladRassokhin, this is exactly the kind of information I was looking for :)
