### ISSUE TITLE
Support new data sources - 0.7.3

### ISSUE THREAD

**Issue by moh-abk** [VladRassokhin/intellij-hcl#45]
Hi,

Can you please add support for the new [aws_cloudformation_stack](https://www.terraform.io/docs/providers/aws/d/cloudformation_stack.html) data source;

```
data "aws_cloudformation_stack" "network" {
    name = "my-network-stack"
}

resource "aws_instance" "web" {
    ami = "ami-abb07bcb"
    instance_type = "t1.micro"
    subnet_id = "${data.aws_cloudformation_stack.network.outputs["SubnetId"]}"
    tags {
        Name = "HelloWorld"
    }
}
```

It has 9 attributes reference.

**Comment by zfil** [comment]
@VladRassokhin by the way how do you generate the various terraform model json files ? Is this something you do by hand ?

**Comment by VladRassokhin** [comment]
Currently I'm on vacation, so would do that next week or later.
@zfil There's [special branch](https://github.com/VladRassokhin/terraform/tree/f-export-schema) in my fork of terraform and [pull-request](https://github.com/hashicorp/terraform/pull/3508) = to add 'schema' command (since i've no spare time it's not done yet). 
After new version of terraform released I'm rebasing branch to newest tag and then [special script](https://github.com/VladRassokhin/utilities/blob/master/shell-scripts/export-terraform-schemas.sh) generates expected output.

**Comment by zfil** [comment]
Thanks!

With a couple a modification I've been able to rebuild the plugin with the new definitions :)

I didn't really take time to check the correctness but from what I see it seems to be fine excepted for the local-exec and remote-exec provisioners.

```
$ ./pkg/linux_amd64/terraform schemas -json -indent -type provisioner remote-exec
{
  "name": "remote-exec",
  "type": "provisioner",
  "schema": {}
}

```

**Comment by VladRassokhin** [comment]
Updated Terraform model to 0.7.4 in plugin version 0.5.9
