### ISSUE TITLE
CloudFront forwarded_values should have cookies as required.

### ISSUE THREAD

**Issue by kitsunde** [VladRassokhin/intellij-hcl#67]
This gets auto generated: 

    "forwarded_values" {
      query_string = false
    }

But without `cookies` an exception gets logged. 

> missing required field, CreateDistributionWithTagsInput.DistributionConfigWithTags.DistributionConfig.DefaultCacheBehavior.ForwardedValues.Cookies.

It should be:

    "forwarded_values" {
      query_string = false
      "cookies" {
        forward = "none"
      }
    }

Reference: https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#forwarded-values-arguments

**Comment by VladRassokhin** [comment]
Hi @kitsunde 
Sorry for late response.
After some debugging and [looking into terraform sources](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_cloudfront_distribution.go#L219), I've found that plugin behaviour is correct since `aws_cloudfront_distribution.default_cache_behavior.forwarded_values.cookies` has ['Optional=true' schema](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_cloudfront_distribution.go#L219), and `aws_cloudfront_distribution.cache_behavior.forwarded_values.cookies` has [`Required=true` schema](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_cloudfront_distribution.go#L71).
Please report bug to terraform sources.

**Comment by VladRassokhin** [comment]
Anyway, I've committed workaround.
